name: Hola Mundo

on:
  push:
    branches:
      - main # O la rama en la que quieres que se ejecute, por ejemplo, 'test'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Imprimir Hola Mundo
        env: 
          test: "pablo"
        run: echo "Hola Mundo $env:test $GITHUB_WORKFLOW"

